### ISSUE TITLE
compensateContributors isn't onlyOwner

### ISSUE THREAD

**Issue by colterj199** [district0x/contribution#5]
The top comment contains "this method is called by owner after contribution period ends". If it's meant to be called by the owner, why not make it onlyOwner?

**Comment by madvas** [comment]
`onlyOwner` was removed from this function on purpose after consulting with auditors. The function is safe to be executed by anyone and it prevents scenario when we'd not compensate contributors after the sale.

**Comment by colterj199** [comment]
Interesting... It does increase the attack surface though, but if you're confident that function isn't going to be an issue, then I guess it's just fixing the comment then. 

I don't really understand what that scenario would be though... you'd lose the owner private key? I mean, that's really worst case scenario, but even if that were the case, you could still launch a set of new contracts with a new private key, and only use the contributions from the previous (now unaccessible contract) to set balances on the new one. That's really just a worst case scenario...

**Comment by madvas** [comment]
Yeah, those are all very edge cases, right now it seems to me that adding it would be actually better, because enabling transfers are onlyOwner anyway. 
To understand why it was removed I need to explain to you how distribution contract evolved: At first we had contract that was supposed to serve 3 rounds of contribution periods. Removing onlyOwner made sense, in case we "turned evil" and didn't want to compensate after 2nd or 3rd period. Since tokens would be already tradable on exchanges and having value. With only 1 period this wouldn't make much sense, since enabling transfers requires onlyOwner, which comes after compensation. So I'll probably add it back, thanks you 😁

**Comment by colterj199** [comment]
np, I'm not on my dev machine now but I can send a one-line PR too

**Comment by madvas** [comment]
I've put onlyOwner back
